services:
  loki:
    container_name: loki
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/app 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.loki.rule=Host(`loki.like`)"
      - "traefik.http.routers.loki.entrypoints=web"
      - "traefik.http.services.loki.loadbalancer.server.port=8501"
    networks:
      - traefik-net
    ports:
      - "2007:8501"

networks:
  traefik-net:
    external: true
